"""
`NSM/configs/default_config.json` is generated by
`NSM/configs/generate_sdf_default_config.py`. Nothing enforced that, so the two drifted:
`axis_align` was commented out of the generator without regenerating, and `eikonal_weight`
was added to the generator and never propagated. Both were inert, but the next drift might
not be.
"""

import json
import os

import pytest

import NSM
from NSM.configs.generate_sdf_default_config import DEFAULT_CONFIG_PATH
from NSM.configs.generate_sdf_default_config import config as generated_config

SHIPPED_PATH = os.path.join(os.path.dirname(NSM.__file__), "configs", "default_config.json")


@pytest.fixture(scope="module")
def shipped_config():
    with open(SHIPPED_PATH) as f:
        return json.load(f)


def test_generator_writes_to_the_shipped_path():
    """A generator that writes somewhere else is how the two drifted in the first place."""
    assert os.path.realpath(DEFAULT_CONFIG_PATH) == os.path.realpath(SHIPPED_PATH)


def test_shipped_config_matches_the_generator(shipped_config):
    # Round-trip the generator through JSON so Python values (None, True) compare against
    # their serialized forms rather than failing on type.
    expected = json.loads(json.dumps(generated_config))

    assert shipped_config == expected, (
        "NSM/configs/default_config.json is out of sync with its generator. "
        "Regenerate with: python -m NSM.configs.generate_sdf_default_config"
    )


def test_importing_the_generator_writes_nothing(tmp_path, monkeypatch):
    """
    The write used to run at import time, into the caller's cwd, so merely importing this
    module littered whatever directory you happened to be in.
    """
    monkeypatch.chdir(tmp_path)

    import importlib

    import NSM.configs.generate_sdf_default_config as module

    importlib.reload(module)

    assert list(tmp_path.iterdir()) == []


# ---------------------------------------------------------------------------
# Keys that do nothing — plan §6.1's last checkbox
# ---------------------------------------------------------------------------

NSM_ROOT = os.path.dirname(NSM.__file__)

#: Modules that do not count as a reader, and the ruling that says so. The config
#: generator holds every key name by definition. The other three are what ``docs/SCOPE.md``
#: puts outside the documented surface: §2.2 (quarantined), §2.1 (unsupported until someone
#: needs it, and broken -- #51), §2.4 (deferred research). A key read only by one of those
#: does nothing on any path a user of the library can take, which is what §6.1 is asking
#: about. Same three exemptions as the docstring gate in ``.flake8`` and the ``verbose``
#: sweep in ``test_observability``, for the same reason.
NOT_A_READER = (
    "generate_sdf_default_config.py",
    "train_deep_sdf_multi_head.py",
    "reconstruct_latent_S3.py",
)


def _live_sources():
    for root, _dirs, files in os.walk(NSM_ROOT):
        if "deprecated" in root or "__pycache__" in root:
            continue
        for name in files:
            if not name.endswith(".py") or name in NOT_A_READER:
                continue
            with open(os.path.join(root, name), encoding="utf-8") as handle:
                yield handle.read()


LIVE_SOURCES = list(_live_sources())


def _key_appears_anywhere(key):
    return any(key in source for source in LIVE_SOURCES)


def _train_deep_sdf_source():
    with open(os.path.join(NSM_ROOT, "train", "train_deep_sdf.py"), encoding="utf-8") as handle:
        return handle.read()


def test_every_shipped_key_is_read_or_names_a_dataset_parameter(shipped_config):
    """
    §6.1's last checkbox: find the config keys that silently do nothing.

    It looked for keys "whose implementing branch is commented out". The sweep found the
    stronger form — **no branch at all**: eight of the 121 shipped keys had no occurrence
    anywhere in a live ``NSM/`` module outside this config and its generator.

    Investigating them changed what the defect *is*. NSM never builds a dataset from a
    config — ``train_deep_sdf(config, model, sdf_dataset)`` takes one already built — so
    the dataset half of this file is a specification the user translates into
    ``MultiSurfaceSDFSamples`` arguments by hand, and **six of the eight named a real
    parameter under a different spelling**: ``n_pts_per_object``/``n_pts``,
    ``percent_near_surface``/``p_near_surface``,
    ``percent_further_from_surface``/``p_further_from_surface``,
    ``random_function``/``rand_function``, ``normalize_pts``/``norm_pts``,
    ``dataset_uniform_pts_buffer``/``uniform_pts_buffer``. Eighteen other keys already
    used the constructor's spelling, so the file was inconsistent with itself and unusable
    as ``**kwargs``. Those six are renamed; ``decoder_type`` and ``sdf_skip_connection``
    named nothing on either ``model_type`` path and are deleted.

    Hence the two-clause rule, which is what makes this checkable rather than a one-off:
    a shipped key is legitimate if NSM reads it **or** if it names a dataset-constructor
    parameter the user is expected to pass. A new key that does neither goes red here.

    **"Reads it" excludes the three modules ``SCOPE`` puts outside the documented
    surface** -- see ``NOT_A_READER``. The first version of this test did not, and counted
    ``train_deep_sdf_multi_head`` as a reader, which hid the four ``SAMPLE_DIFFICULTY_LX``
    keys below: they are read by the broken multi-head trainer and by the quarantined one,
    and by nothing a user can run. A sweep that accepts an unsupported module as a reader
    reports the absence of exactly the keys §6.1 is looking for.

    The substring search is the loose direction on purpose — a key mentioned only in a
    comment counts as read — so anything this reports is dead beyond argument. Tightening
    it would need a resolver for ``config[name]`` where ``name`` is a variable.
    """
    import inspect

    from NSM.datasets.sdf_dataset import MultiSurfaceSDFSamples

    constructor = set(inspect.signature(MultiSurfaceSDFSamples.__init__).parameters)
    orphans = sorted(
        key
        for key in shipped_config
        if not _key_appears_anywhere(key)
        and key not in constructor
        and key not in SAMPLE_DIFFICULTY_LX
    )
    assert orphans == [], f"shipped config keys nothing reads and no constructor names: {orphans}"


#: The one exception, and it is named rather than absorbed. These four ship, and the only
#: code that reads them is ``train_deep_sdf_multi_head`` (#51-broken, ``SCOPE`` §2.1) and
#: ``train/deprecated/train_deep_sdf_orig`` (§2.2) -- so on every supported path they do
#: nothing, which is ``KNOWN_ISSUES`` § Open's "``sample_difficulty_lx`` shipped but
#: unimplemented". They are **not** deleted, because #18 is the plan to make them live:
#: port the inverse-Lx branch out of the quarantined trainer at §8.0.P. If #18 ever closes
#: as won't-do, this tuple goes and the keys go with it.
SAMPLE_DIFFICULTY_LX = frozenset(
    {
        "sample_difficulty_lx",
        "sample_difficulty_lx_schedule",
        "sample_difficulty_lx_cooldown",
        "sample_difficulty_lx_epsilon",
    }
)


def test_the_sample_difficulty_lx_keys_are_read_by_nothing_supported(shipped_config):
    """
    #18, pinned so the exemption above cannot quietly become permanent.

    All four ship. ``train_deep_sdf`` -- the trainer ``SCOPE`` supports -- reads
    ``sample_difficulty_weight`` and stops there; the ``elif`` that would read these is in
    ``train_deep_sdf_multi_head`` and in ``train/deprecated/train_deep_sdf_orig``. Setting
    them in a config for a supported run changes nothing and says nothing, which is the
    §6.1 hazard in its original "the implementing branch is elsewhere" form.

    This goes red the day the port lands, which is the point: at that moment the keys
    become live and belong in the main assertion above rather than in an exemption.
    """
    assert SAMPLE_DIFFICULTY_LX <= set(shipped_config)
    supported = os.path.join(NSM_ROOT, "train", "train_deep_sdf.py")
    with open(supported, encoding="utf-8") as handle:
        source = handle.read()
    assert "sample_difficulty_weight" in source
    assert not any(key in source for key in SAMPLE_DIFFICULTY_LX)


def test_the_trainer_passes_chamfer_norm_commented_out():
    """
    #56's evidence that resolving ``chamfer_norm`` moves no number: the only place a
    config could reach it is commented out, so every training run has always taken
    ``get_mean_errors``' default.
    """
    source = _train_deep_sdf_source()
    assert "# chamfer_norm" in source
    assert "chamfer_norm=" not in source


def test_no_shipped_config_carries_a_chamfer_norm_key(shipped_config):
    """The other half: there is no key for the commented-out argument to have read."""
    assert "chamfer_norm" not in shipped_config


# ---------------------------------------------------------------------------
# The predicate, not the data — plan §8.0.R
# ---------------------------------------------------------------------------


def _literals_in_live_sources():
    """
    Every string literal in a live ``NSM/`` module, by AST.

    The tightening the sweep above says it cannot have. Its docstring defends the
    substring match as "a key mentioned only in a comment counts as read" and adds that
    tightening it "would need a resolver for ``config[name]`` where ``name`` is a
    variable" -- which conflates two different tightenings. Matching *string literals*
    needs no resolver: the loose direction is preserved (a literal anywhere counts, in a
    docstring or a ``dict`` far from any config read), and what stops counting is a key
    that only ever appears as a **substring of an identifier**.
    """
    import ast

    literals = set()
    for source in LIVE_SOURCES:
        for node in ast.walk(ast.parse(source)):
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                literals.add(node.value)
    return literals


LIVE_LITERALS = _literals_in_live_sources()


@pytest.mark.xfail(strict=True, reason="§8.0.R commit 4: the six keys are dispositioned")
def test_every_shipped_key_appears_as_a_literal_or_names_a_parameter(shipped_config):
    """
    §8.0.R. The sweep above matches substrings, and six shipped keys pass it only because
    their name is a substring of an unrelated identifier or of a keyword argument being
    passed somewhere else:

    ======================  =========================================  ==================
    key                     what hid it                                disposition
    ======================  =========================================  ==================
    ``n_val``               ``_run_validation``                        deleted
    ``modulated``           ``modulated_periodic_activations``         deleted
    ``entity``              ``identity`` (the code-reg prior)          deleted
    ``cache``               ``empty_cache``                            deleted
    ``seed``                ``seed=seed`` in ``reconstruct/main``      renamed
    ``model_type``          ``model_type=`` in ``recon_evaluation``    kept
    ======================  =========================================  ==================

    Two of the six collide with an identifier rather than a comment, which is the class
    the older docstring's justification does not cover. ``seed`` named a real dataset
    parameter under a different spelling (``random_seed``) -- §8.0.N's own disposition for
    the six it found that way -- and ``model_type`` names ``load_model``'s own argument,
    which is why the second clause widens from the dataset constructor to ``load_model``
    as well. That widening is not a loophole for this one key: it is the same rule the
    dataset clause already states, applied to the other entry point a user drives with
    this file.

    This is the third time in this plan that a sweep was wrong in its *predicate* rather
    than its data -- §6.1's first pass took an unsupported module as a reader, §8.0.N
    corrected that reader set and left the match granularity, and this corrects the
    granularity.
    """
    import inspect

    from NSM.datasets.sdf_dataset import MultiSurfaceSDFSamples
    from NSM.models.loader import load_model

    named = set(inspect.signature(MultiSurfaceSDFSamples.__init__).parameters)
    named |= set(inspect.signature(load_model).parameters)

    orphans = sorted(
        key
        for key in shipped_config
        if key not in LIVE_LITERALS and key not in named and key not in SAMPLE_DIFFICULTY_LX
    )

    assert orphans == [], (
        "shipped config keys that appear as no string literal in a live NSM module and "
        f"name no MultiSurfaceSDFSamples or load_model parameter: {orphans}"
    )
