"""
``NSM/configs/default_config.json`` is generated by ``generate_sdf_default_config.py``, and
every key in it does something.
"""

import ast
import importlib
import inspect
import json
import os

import NSM
from NSM.configs.generate_sdf_default_config import DEFAULT_CONFIG_PATH
from NSM.configs.generate_sdf_default_config import config as generated_config
from NSM.datasets.sdf_dataset import MultiSurfaceSDFSamples
from NSM.models.loader import load_model

NSM_ROOT = os.path.dirname(NSM.__file__)
SHIPPED_PATH = os.path.join(NSM_ROOT, "configs", "default_config.json")

#: Modules that do not count as a reader of a key. The generator holds every key by
#: definition. ``reconstruct_latent_S3`` is outside the documented surface (``SCOPE``
#: §2.4). Shrink this in the commit that deletes a listed module: an exemption that
#: outlives its module reports a dead key as live.
NOT_A_READER = ("generate_sdf_default_config.py", "reconstruct_latent_S3.py")


def _shipped():
    with open(SHIPPED_PATH, encoding="utf-8") as handle:
        return json.load(handle)


def test_the_shipped_file_is_the_generators_output():
    """The two drifted twice before this existed: ``axis_align`` and ``eikonal_weight``."""
    assert os.path.realpath(DEFAULT_CONFIG_PATH) == os.path.realpath(SHIPPED_PATH)
    assert _shipped() == json.loads(json.dumps(generated_config)), (
        "default_config.json is out of sync with its generator. "
        "Regenerate with: python -m NSM.configs.generate_sdf_default_config"
    )


def test_importing_the_generator_writes_nothing(tmp_path, monkeypatch):
    """The write used to run at import, into whatever directory the caller was in."""
    import NSM.configs.generate_sdf_default_config as module

    monkeypatch.chdir(tmp_path)
    importlib.reload(module)
    assert list(tmp_path.iterdir()) == []


def test_every_shipped_key_is_read_or_names_a_parameter():
    """
    A key is live if it appears as a string literal in a live ``NSM/`` module, or if it
    names a ``MultiSurfaceSDFSamples`` or ``load_model`` parameter. NSM never builds a
    dataset from a config, so the dataset half of the file is a specification the caller
    passes to the constructor.

    String literals, not substrings. A substring match passed six dead keys because each
    was part of an unrelated identifier: ``n_val`` (``_run_validation``), ``modulated``,
    ``entity`` (``identity``), ``cache`` (``empty_cache``), ``seed`` and ``model_type``.
    """
    literals = set()
    for root, _dirs, files in os.walk(NSM_ROOT):
        for name in files:
            if name.endswith(".py") and name not in NOT_A_READER:
                with open(os.path.join(root, name), encoding="utf-8") as handle:
                    tree = ast.parse(handle.read())
                literals |= {
                    node.value
                    for node in ast.walk(tree)
                    if isinstance(node, ast.Constant) and isinstance(node.value, str)
                }

    named = set(inspect.signature(MultiSurfaceSDFSamples.__init__).parameters)
    named |= set(inspect.signature(load_model).parameters)
    orphans = sorted(key for key in _shipped() if key not in literals and key not in named)
    assert orphans == []


def test_nothing_can_set_chamfer_norm_during_training():
    """
    #56's evidence that giving ``chamfer_norm`` one default moves no number: the trainer's
    argument is commented out and no config carries the key, so every training run has
    used ``get_mean_errors``' default.
    """
    with open(os.path.join(NSM_ROOT, "train", "train_deep_sdf.py"), encoding="utf-8") as handle:
        source = handle.read()
    assert "# chamfer_norm" in source and "chamfer_norm=" not in source
    assert "chamfer_norm" not in _shipped()
